[package]
name = "rumikan-kernel-lib"
version = "0.1.0"
authors = ["ocadaruma <ocadaruma@gmail.com>"]
edition = "2018"

[dependencies]
rumikan-shared = { path = "../shared" }
bit_field = "0.10.1"
log = { version = "0.4.14", default-features = false }
