[package]
name = "rumikan-bootloader"
version = "0.1.0"
authors = ["ocadaruma <ocadaruma@gmail.com>"]
edition = "2018"

[dependencies]
uefi = "0.8.0"
uefi-services = "0.5.0"
log = { version = "0.4.14", default-features = false }
rumikan-shared = { path = "../shared" }
